global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'api'
    static_configs: [{ targets: ['api:8000'] }]
    metrics_path: /metrics

  - job_name: 'scheduler'
    static_configs: [{ targets: ['scheduler:9100'] }]

  - job_name: 'workers'
    static_configs: [{ targets: ['worker1:9200','worker2:9200'] }]
